spring:
  ai:
    ollama:
      chat:
        model: llama3
        base-url: http://ollama:11434
      embedding:
        model: nomic-embed-text
        base-url: http://ollama:11434
    vectorstore:
      type: chroma
      chroma:
        initialize-schema: true
        endpoint: http://chroma:8000
